version: '3.3'
services:
  poker:
    container_name: poker-victorys_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    networks:
      - production-network   
   
  pgadmin:
    container_name: poker-victorys_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ricardo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - '9090:80'
    networks:
      - production-network  
    
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"  
      
networks: 
  production-network:
        driver: bridge


