score:
  rabbitmq:
    exchange: score.exchange
    queue: score.queue
    routingkey: score.routingkey

spring:
  application:
    name: score-producer
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka 
          
server:
  port: 8092
 