
spring:
  application:
    name: consumer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8089
  
  
#  spring.main.allow-bean-definition-overriding=true
  