server:
  port: 5555
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka 
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "routes"     
        
zuul:
  routes:
    player:
      path: /**
      service-id: player
      strip-prefix: true
    producer:
      path: /**
      service-id: score-producer
      strip-prefix: true
